// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dyqpsggozeyeurrwxowi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5cXBzZ2dvemV5ZXVycnd4b3dpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNTMxMjksImV4cCI6MjA1OTYyOTEyOX0.mCHjVdHx1G0r_IGhpRvtPYTQbUNZmhkwLYxQdY5o0hs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);