
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emgrwjijyzgtjoynjvmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtZ3J3amlqeXpndGpveW5qdm1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3OTcwMjksImV4cCI6MjA2NDM3MzAyOX0.C_Uzjx0_ejEiKI6smqRIGPBs9cZaegZHAq9mtzDc9GE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
