// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rvdjgnfnnfrpqwpxlslc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2ZGpnbmZubmZycHF3cHhsc2xjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0Njg3NDEsImV4cCI6MjA2NDA0NDc0MX0.s4ZLE6U8QFq19NW0EPvcJu7hC32fOJHgSvLCL_s3hMk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);